title = "Workload get example"

[global]
block_size = 5
Duration = "160s"
server="29mbw8bh6b.execute-api.us-east-1.amazonaws.com"
port="443"
TLSMode=true
 [global.StatusCodesAcceptance]
  200 = 100.0
  204 = 100.0
  205 = 100.0

[workloads]
   [workloads.get]
    generator="performance"
    name="serverless get"
    container="dev"
    Target="hello-world"
    Duration = "10s"
    TYPE="GET"
    count=0
    workers=100